Add -ltinfo to LIBS variable in hstr.pro
When building in an Amazon Linux AMI from the tarball,
the `make` command failed with error:
`undefined reference to symbol 'keypad'`, which is part
of the libtinfo5.so. By adding -ltinfo to the libraries
this was solved and the application could be built and
used successfully.